# GitLab CI/CD configuration for GitLab Pages
pages:
  stage: deploy
  script:
    # Create the public directory (GitLab Pages serves from this directory)
    - mkdir -p public

    # Copy all necessary files to the public directory
    - cp index.html public/
    - cp script.js public/
    - cp styles.css public/
    - cp *.svg public/

    # Print deployment info
    - echo "Deploying theme switcher to GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - main  # This job will only run on the main branch
